# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e463eaf41c9646ad4a8d472c2566c28e8369abcb54fef8424f39cd90176eb9dd979d43f4314453e92d8b37a2391b6a5bbbd0820e0ddab3917f4cda18e0f3533

test:
  secret_key_base: cfc4cdf60b6d640e0d746fff6c1122f1694b6b55e3453576c4fa24388bbe184512f8f23667f31a9a06cb3334451d7c9f5bd8a00d006fba294fbff4af944f7eee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
